### ISSUE TITLE
Switch to HTTPS

### ISSUE THREAD

**Issue by davidism** [pythonsd/pythonsd.org#106]
Use letsencrypt to generate a cert. I don't know our hosting details though. cc @macro1

**Comment by davidfischer** [comment]
The Django parts are hosted on heroku but the static parts are hosted on GitHub pages.

**Comment by macro1** [comment]
Currently the server users see is a Django site hosted on Heroku. There are
proxy views that reach out to Github to get the static site for existing
content. The idea was that a dynamic site would give us more flexibility,
and allow developers wanting some web development experience something more
authentic.

Anyway, regarding HTTPS, I think it would be a configuration change in
Heroku. Both David Fischer and I are able to make that change currently.

**Comment by davidfischer** [comment]
The site is now HTTPS. There are a few side effects that need to be fixed but those are minor (mostly jQuery needed for the Meetup widget which is already broken).

This does introduce the need for us to canonicalize the domain. This requires changes to the Django app and I created an issue there: https://github.com/pythonsd/pythonsd-django/issues/19
