### ISSUE TITLE
Upgrade Pelican

### ISSUE THREAD

**Issue by macro1** [pythonsd/pythonsd.org#61]
For some reason only Pelican 3.5.0 is available on PyPI, and there are some changes in the way sites are generated and run. We should transition off the old version of Pelican.

**Comment by davidfischer** [comment]
While I'm not opposed to upgrading Pelican, older versions of Pelican are now available.

https://pypi.python.org/pypi/pelican/3.1.1#downloads

**Comment by macro1** [comment]
I'm going to close, as I opened this issue. Like you said, the older versions are available on PyPI again, and I think a couple of us wouldn't mind some of the content moving to the [Django project](https://github.com/pythonsd/pythonsd-django).
