### ISSUE TITLE
Record video of meetup presentations

### ISSUE THREAD

**Issue by davidfischer** [pythonsd/pythonsd.org#7]
I don't have access to AV equipment, but if somebody does or would like to take point on this, I think it would be a great service to the group.

**Comment by davidfischer** [comment]
I have Kendall's video camera. However, somebody other than main organizer (the person introducing people and/or talking) has to actually film. Also, I think getting a separate dedicated mic would improve the audio considerably.

**Comment by macro1** [comment]
@Sonictherocketman: Did you mention once you have some audio equipment?

**Comment by Sonictherocketman** [comment]
I do yes. I have a mixer, multiple mics and cables for it all. What are you thinking?

**Comment by davidfischer** [comment]
We now have a YouTube channel: https://www.youtube.com/channel/UCXU-oZwaHnoYUhja_yrrrGg. Long story short, I'm going to repurpose this issue to be linking to YouTube from the website.

Unless we get a recording company to come record our talks (which ChiPy does) I think the best way to record talks is to screen record on the machine giving the talk and record audio through the microphone. The most recent talks on our YouTube channel (eg. [this one](https://www.youtube.com/watch?v=OtZhbtjaYBY)) use that method and it works well.

I am interested in trying something like a [video capture device](https://www.amazon.com/dp/B0779ZJZX3/) which could sit between the laptop and the projector and it records the video (and maybe audio) stream. However, this would require a lot of testing of various moderately expensive products.

**Comment by davidfischer** [comment]
> Long story short, I'm going to repurpose this issue to be linking to YouTube from the website.

I'm actually going to close this in favor of a new issue around linking to the YouTube channel: https://github.com/pythonsd/pythonsd.org/issues/109
