### ISSUE TITLE
Mention Collective 1939 Open Date

### ISSUE THREAD

**Issue by davidfischer** [pythonsd/pythonsd.org#86]
They're shooting to begin crowdfunding on March 15

**Comment by macro1** [comment]
Is there a link with more info or something? I don't know anything about them.

**Comment by davidfischer** [comment]
Their address is http://collective1939.strikingly.com/
No major details yet other than the address and that they're a coworking space.

**Comment by davidfischer** [comment]
I guess we can close this.
